server:
  port: 9002
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: greenheartum
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenheart?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
feign:
  hystrix:
    enabled: true