server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: greenheartuser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenheart?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #mapper-locations: classpath:/mapper/*.xml  192.168.3.9

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 6000000